> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


#  5 useful Numpy Array Operations


## Introduction

Numpy is a library in python that allows us to perform matrix functions and to also work with arrays. Numpy was created so that we could perform MATLAB functions in python. It is a very useful library when handeling data science related operations. I have picked five of my favourite numpy functions below.



- np.unique
- np.linalg.eig
- np.hstack
- np.vstack
- np.split

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [1]:
!pip install jovian --upgrade -q

In [2]:
import jovian

In [3]:
jovian.commit(project='numpy-array-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "venkatasaigopal01/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/venkatasaigopal01/numpy-array-operations


'https://jovian.ai/venkatasaigopal01/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [4]:
import numpy as np

In [5]:
# List of functions explained 
function1 = np.unique  # (change this)
function2 = np.linalg.eig
function3 = np.hstack
function4 = np.vstack
function5 = np.split

## Function 1 - np.unique

Returns unique words of the given input array.

In [6]:
# Example 1 - working (change this)
arr1 = [[1, 2, 1], 
        [3, 5, 2]]

np.unique(arr1)

array([1, 2, 3, 5])

returns unique integers.

In [7]:
# Example 2 - working
arr1 = ["v", "a", "w", "w"]

np.unique(arr1)

array(['a', 'v', 'w'], dtype='<U1')

returns unique char.

In [8]:
# Example 3 
arr1 = ["a", 2]

np.unique(arr1)

array(['2', 'a'], dtype='<U1')

Some closing comments about when to use this function.

In [9]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "venkatasaigopal01/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/venkatasaigopal01/numpy-array-operations


'https://jovian.ai/venkatasaigopal01/numpy-array-operations'

## Function 2 - ???

np.linalg.eig returns eigen values and eigen vectors.

In [10]:
# Example 1 - working
arr1 = [[1, 0], [0, 1]]

np.linalg.eig(arr1)

(array([1., 1.]),
 array([[1., 0.],
        [0., 1.]]))

In [11]:
# Example 2 - working
arr1 = [[1, 0, 3], [0, 1, 4], [1, 2, 4]]

np.linalg.eig(arr1)

(array([ 6.14005494,  1.        , -1.14005494]),
 array([[-4.18364208e-01, -8.94427191e-01, -5.51598885e-01],
        [-5.57818944e-01,  4.47213595e-01, -7.35465181e-01],
        [-7.16805005e-01,  1.23924678e-16,  3.93483974e-01]]))

In [12]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 0, 3], [0, 1, 4]]

np.linalg.eig(arr1)

LinAlgError: Last 2 dimensions of the array must be square

Explanation : function only works with square matrix with non zero delt values(non singular).

In [ ]:
jovian.commit()

## Function 3 - ???

 hstack you can appened data horizontally.
 
 numpy.hstack(tup)

In [ ]:
# Example 1 - working
arr1 = np.array([1,2,3])

arr2 = np.array([4,5,6])

np.hstack((arr1,arr2))

stacking two arrays horizontaly.

In [ ]:
# Example 2 - working
arr1 = np.array([])

arr2 = np.array([1,2,3])

np.hstack((arr1,arr2))

stacking two arrays horizontaly.

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1,3]])

arr2 = np.array([1,2,3])

np.hstack((arr1,arr2))

Explanation : when the two arrays of different row dimension are given then this function doesn't work. 

In [ ]:
jovian.commit()

## Function 4 - ???


 vstack you can appened data horizontally.
 
 numpy.vstack(tup)

In [ ]:
# Example 1 - working
arr1 = np.array([1,2,3])

arr2 = np.array([2,3,4])

np.vstack((arr1,arr2))

In [ ]:
# Example 2 - working
arr1 = np.array([[1,2,3],[1,3,3]])

arr2 = np.array([4,5,6])

np.vstack((arr1,arr2))

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([])

arr2 = np.array([4,5,6])

np.vstack((arr1,arr2))


Explanation:when the two arrays of different column dimension are given then this function doesn't work. 

In [13]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "venkatasaigopal01/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/venkatasaigopal01/numpy-array-operations


'https://jovian.ai/venkatasaigopal01/numpy-array-operations'

## Function 5 - ???

Split an array into multiple sub-arrays.

numpy.split(ary, indices_or_sections, axis=0)


In [14]:
# Example 1 - working
arr1 = np.array([[1, 2, 3],[1, 3, 3],[4, 5, 6]])

np.split(arr1, 3, axis = 1)

[array([[1],
        [1],
        [4]]),
 array([[2],
        [3],
        [5]]),
 array([[3],
        [3],
        [6]])]

Explanation about example

In [15]:
# Example 2 - working
arr1 = np.array([[1, 2, 3],[1, 3, 3],[4, 5, 6]])
np.split(arr1, 1, axis = 0)

[array([[1, 2, 3],
        [1, 3, 3],
        [4, 5, 6]])]

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = np.array([[1, 2, 3],[1, 3, 3],[4, 5, 6]])
np.split(arr1, 2, axis = 0)

ValueError: array split does not result in an equal division

Explanation: If indices_or_sections is given as an integer, but a split does not result in equal division

In [17]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "venkatasaigopal01/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/venkatasaigopal01/numpy-array-operations


'https://jovian.ai/venkatasaigopal01/numpy-array-operations'

## Conclusion

This notebook has covered 5 functions that will be very useful to the reader while working with data manipulation tasks and neural networks

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [19]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "venkatasaigopal01/numpy-array-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/venkatasaigopal01/numpy-array-operations


'https://jovian.ai/venkatasaigopal01/numpy-array-operations'